# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu alan bos birakilamaz!', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='media/urun_resimleri/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Link, otomatik alinir. Degistirmeyiniz!', max_length=80, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu alan bos birakilamaz!', max_length=255)),
                ('price', models.CharField(help_text='Fiyat bos birakilamaz!', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='media/urun_resimleri/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('definition', models.TextField(blank=True, help_text='Urunun aciklamasini giriniz!', null=True)),
                ('slug', models.SlugField(help_text='Link, otomatik alinir. Degistirmeyiniz!', max_length=80, null=True)),
                ('viewCount', models.IntegerField(default=0, editable=False)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Bu alan bos birakilamaz!', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='media/urun_resimleri/%Y/%m/%d')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Link, otomatik alinir. Degistirmeyiniz!', max_length=80, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.MainCategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory'),
        ),
    ]
